package com.chakro.server.agent.tool;

import dev.langchain4j.agent.tool.Tool;
import org.apache.poi.xwpf.usermodel.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.UUID;

/**
 * LangChain4j tool for generating downloadable document files
 * from proposal content using Apache POI (DOCX format).
 */
@Component
public class DocumentGenerationTool {

    private static final Logger log = LoggerFactory.getLogger(DocumentGenerationTool.class);

    @Value("${vbdp.file-storage-path:./generated-proposals}")
    private String fileStoragePath;

    @Tool("Generates a professional DOCX document file from the provided proposal content. "
            + "Returns the file path of the generated document.")
    public String generateDocumentFile(String content) {
        if (content == null || content.isBlank()) {
            return "Error: No content provided for document generation.";
        }

        try {
            // Ensure storage directory exists
            Path storagePath = Paths.get(fileStoragePath);
            Files.createDirectories(storagePath);

            String fileName = "proposal_" + UUID.randomUUID() + ".docx";
            Path filePath = storagePath.resolve(fileName);

            try (XWPFDocument document = new XWPFDocument()) {
                // Title
                XWPFParagraph titleParagraph = document.createParagraph();
                titleParagraph.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun titleRun = titleParagraph.createRun();
                titleRun.setText("PROPOSAL DOCUMENT");
                titleRun.setBold(true);
                titleRun.setFontSize(18);
                titleRun.setFontFamily("Calibri");
                titleRun.addBreak();

                // Subtitle
                XWPFParagraph subtitleParagraph = document.createParagraph();
                subtitleParagraph.setAlignment(ParagraphAlignment.CENTER);
                XWPFRun subtitleRun = subtitleParagraph.createRun();
                subtitleRun.setText("Generated by Chakro AI — Virtual Business Development Partner");
                subtitleRun.setItalic(true);
                subtitleRun.setFontSize(10);
                subtitleRun.setFontFamily("Calibri");
                subtitleRun.addBreak();
                subtitleRun.addBreak();

                // Disclaimer
                XWPFParagraph disclaimerParagraph = document.createParagraph();
                XWPFRun disclaimerRun = disclaimerParagraph.createRun();
                disclaimerRun.setText("DISCLAIMER: This is a non-binding draft proposal generated "
                        + "by an AI system. It requires human review and approval before submission.");
                disclaimerRun.setItalic(true);
                disclaimerRun.setFontSize(9);
                disclaimerRun.setColor("FF0000");
                disclaimerRun.addBreak();

                // Content - split by sections (double newlines)
                String[] sections = content.split("\\n\\n+");
                for (String section : sections) {
                    String trimmedSection = section.trim();
                    if (trimmedSection.isEmpty()) continue;

                    XWPFParagraph paragraph = document.createParagraph();

                    // Detect headers (lines starting with # or all caps short lines)
                    if (trimmedSection.startsWith("#")) {
                        String headerText = trimmedSection.replaceAll("^#+\\s*", "");
                        XWPFRun headerRun = paragraph.createRun();
                        headerRun.setText(headerText);
                        headerRun.setBold(true);
                        headerRun.setFontSize(14);
                        headerRun.setFontFamily("Calibri");
                    } else if (trimmedSection.length() < 80
                            && trimmedSection.equals(trimmedSection.toUpperCase())) {
                        XWPFRun headerRun = paragraph.createRun();
                        headerRun.setText(trimmedSection);
                        headerRun.setBold(true);
                        headerRun.setFontSize(13);
                        headerRun.setFontFamily("Calibri");
                    } else {
                        // Regular content
                        String[] lines = trimmedSection.split("\\n");
                        for (int i = 0; i < lines.length; i++) {
                            XWPFRun run = paragraph.createRun();
                            run.setText(lines[i].trim());
                            run.setFontSize(11);
                            run.setFontFamily("Calibri");
                            if (i < lines.length - 1) {
                                run.addBreak();
                            }
                        }
                    }
                }

                // Write to file
                try (FileOutputStream out = new FileOutputStream(filePath.toFile())) {
                    document.write(out);
                }
            }

            log.info("Generated proposal document: {}", filePath.toAbsolutePath());
            return filePath.toAbsolutePath().toString();

        } catch (IOException e) {
            log.error("Failed to generate document file: {}", e.getMessage());
            return "Error generating document: " + e.getMessage();
        }
    }
}
